pool:
  vmImage: 'macos-latest'

  
steps:

- task: CmdLine@2
  inputs:
    script: |
      /usr/bin/xcodebuild -exportArchive -exportFormat ipa -archivePath /Users/runner/work/1/s/iOSWKWebViewAppTemplateCookiesWorkLikeACharm.xcarchive -exportPath /Users/runner/work/1/s/output/




      