pool:
  vmImage: 'macos-latest'

  
steps:

- task: Xcode@5
  inputs:
    actions: 'build'
    configuration: 
    sdk: 'iphoneos'
    packageApp: true
    exportPath: 'output/'
- task: CopyFiles@2
  inputs:
    contents: '**/*.ipa'
    targetFolder: '$(build.artifactStagingDirectory)'
    overWrite: true
    flattenFolders: true
- task: PublishBuildArtifacts@1
  inputs:
    pathtoPublish: '$(build.artifactStagingDirectory)'
    artifactName: 'drop'
    publishLocation: 'Container'
- task: CmdLine@2
  inputs:
    script: |
      ls -R | grep ":$" | sed -e 's/:$//' -e 's/[^-][^\/]*\//--/g' -e 's/^/   /' -e 's/-/|/'
      find *.app
      echo ok

      