pool:
  vmImage: 'macos-latest'

  
steps:


- task: CmdLine@2
  inputs:
    script: |
      /usr/bin/xcodebuild clean build CODE_SIGN_IDENTITY="" CODE_SIGNING_REQUIRED=NO
      /usr/bin/xcodebuild -exportArchive -archivePath /Users/runner/work/1/s/iOSWKWebViewAppTemplateCookiesWorkLikeACharm.xcarchive -exportPath /Users/runner/work/1/s/output/




      